### ISSUE TITLE
Proposal - Make can-stache even more like JavaScript

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache#528]
> This was discussed on a [recent live stream (10:42)](https://youtu.be/wjBBXb1j9ZU?t=10m42s), with follow-up discussion at [55:36](https://youtu.be/wjBBXb1j9ZU?t=55m36s).

## Tasks 

- [x] Prototype for(of)
- [x] Prototype `let foo=bar,zed=ted`
- [x] Make sure it works with `can-stache-bindings`.  I think writing to these variables needs to be prevented unless defined.
- [x] Make sure it works with `can-component`
- [x] Allow let to be used as a place holder.
- [ ] Figure out what to do with leakScope.
- [x] Update all examples to use `this.key`?

## Problem and Solutions

Learning stache can still be a step that gets in the way of fully enjoying CanJS. I'd like to simplify it in a few ways while maintaining as much backward compatibility as possible.

In short, I'd like to fix the following problems:

- Hard to remember `each` syntax
- Weird scope lookup rules. `{{../../}}`
- ViewModels use `this.fullName`, why doesn't `can-stache`?

> Until we have JSX integration and it has the abilities to things like two-way binidngs, we should continue making `stache` a great template engine.

### Hard to remember `each` syntax

I find myself having to take a moment to remember `{{# each(todos, todo=value) }}`. I'd like to support `{{# for(todo of todos) }}` in stache:

Instead of:

```html
{{# each(users, user=value) }}
  <div>
     {{user.name}}
     <ul>
       {{# each(user.todos, todo=value) }}
         <li>{{todo.name}}<li>
       {{/ each }}
     </ul>
  </div>
{{/ each }}
```  

It would be:

```html
{{# for(user of users) }}
  <div>
     {{user.name}}
     <ul>
       {{# for(todo of user.todos) }}
         <li>{{todo.name}}<li>
       {{/ for }}
     </ul>
  </div>
{{/ for }}
```

### Weird scope lookup rules

Things get weird if you have nested loops in CanJS.  Especially with 4.0, the use of `../` or `scope.top` is necessary.  

For example, if there was an `isOwner()` method on the ViewModel that needed a user and todo:

```html
{{# each(users, user=value) }}
  <div>
     {{user.name}}
     <ul>
       {{# each(user.todos, todo=value) }}
         <li>{{todo.name}} {{../../isOwner(../user, todo) }}<li>
       {{/ each }}
     </ul>
  </div>
{{/ each }}
```  

`{{../../isOwner(../user, todo) }}` ... GROSS!

Instead, I'd like to make CanJS able to walk up "closure" scopes automatically:

```html
{{# for(user of users) }}
  <div>
     {{user.name}}
     <ul>
       {{# for(todo of user.todos) }}
         <li>{{todo.name}}  {{ this.isOwner(user, todo) }}<li>
       {{/ for }}
     </ul>
  </div>
{{/ for }}
```  

### Use `this.`

At the last DoneJS Chicago, we had users write something similar to:

```js
can.Component.extend({
  tag: "evil-tinder",
  view: ` <img src="{{currentProfile.img}}"/> `,
  ViewModel: {
    profiles: {
      default(){ return [...]; }
    },
    get currentProfile() {
      return this.profiles.get(0);
    }
  }
});
``` 

They wondered why the `ViewModel` had `this.profiles`, but 
the `view` was `currentProfile.img` and not `this.currentProfile.img`. I would like to start using `this.` to refer to the viewModel.  Fortunately, this is already the case in stache if you aren't in a helper.  The following already works:

```js
can.Component.extend({
  tag: "evil-tinder",
  view: ` <img src="{{this.currentProfile.img}}"/> `,
  ViewModel: {
    profiles: {
      default(){ return [...]; }
    },
    get currentProfile() {
      return this.profiles.get(0);
    }
  }
});
``` 

`for()` loops wouldn't change the current "context", they would only add "closure" scopes. "Closure scopes" is why `this` would work in `this.isOwner(user, todo)`:

```html
{{# for(user of users) }}
  <div>
     {{user.name}}
     <ul>
       {{# for(todo of user.todos) }}
         <li>{{todo.name}}  {{ this.isOwner(user, todo) }}<li>
       {{/ for }}
     </ul>
  </div>
{{/ for }}
```  

But it would also work outside of the for loops as it always has:

```html
Hello, you have  {{this.users.length}}.
{{# for(user of this.users) }}
  <div>
     {{user.name}}
     <ul>
       {{# for(todo of user.todos) }}
         <li>{{todo.name}}  {{ this.isOwner(user, todo) }}<li>
       {{/ for }}
     </ul>
  </div>
{{/ for }}
```  

## Variables 

I'd like to be able to create variables too:

```html
{{let metaData = this.users.metaData}}

Hello, you have  {{this.users.length}}.
{{# for(user of this.users) }}
  <div>
     {{user.name}} is part of {{metaData.clan}}
     <ul>
       {{# for(todo of user.todos) }}
         <li>{{todo.name}}  {{ this.isOwner(user, todo) }}<li>
       {{/ for }}
     </ul>
  </div>
{{/ for }}
```
Or should they work with blocks:

```html
{{# let metaData = this.users.metaData, zed = this.somethingElse}}

  Hello, you have  {{this.users.length}}.
  {{# for(user of this.users) }}
    <div>
       {{user.name}} is part of {{metaData.clan}}
       <ul>
         {{# for(todo of user.todos) }}
           <li>{{todo.name}}  {{ this.isOwner(user, todo) }}<li>
         {{/ for }}
       </ul>
    </div>
  {{/ for }}

{{/ let }}
```

The should probably replace `scope.vars` in this use case:

```js
{{#let selectedDriver}}
  <drivers-list selected:to="selectedDriver"/>
  <driver-edit driver="selectedDriver"/>
{{/let}}
```

## Imports 

It would be nice to import as a variable.  The following are some ideas:

#### Import via magic tags:

```html
{{import foo from "bar"}}
```

### Give `can-import` the ability to update a variable scope

```html
<can-import let:foo="module.default"/>
```

I think the syntax here is weird.  But this is just to give an example.  Perhaps we need a version of `:to` that can write to variables generically:

```html
<my-component thing:to:let="foo">
```

> NOTE: I don't think we need this as we will make sure that `thing:to` can write to a variable if it is declared.

## Slots 

```js
view: `
  <can-slot name="bar" variableName:from="this.viewModelName"/>
`
```

## With leak scope?

Say we have the following, where `<scope-leaker>` has `leakScope: true`:

```
{{# for(thing of things) }}
  <scope-leaker/>
{{/ for }}
```

And `scope-leaker`'s view looks like:

```js
tag: "scope-leaker",
view: `
  {{thing}}
`
```

Should `thing` be able to be read?

## Technical Considerations

- We could create this as a separate project.  `can-jsh`, `can-jashe`.
- If we keep this in `can-stache`, `{{#each}}` and other helpers that change the context (`this`) would be "hidden" from our docs and deprecated.  They would probably last util CanJS 7, possibly beyond that.

**Comment by justinbmeyer** [comment]
Related: https://github.com/canjs/can-stache/issues/505

**Comment by eben-roux** [comment]
I like this.

"Traditionally" a `for` construct would be an incremental loop whereas `foreach` is a pretty established pattern.  I would like `foreach(user in users)`.  That is the c# syntax.  I guessing since "for each" entry "in" the *collection* it executes the block.  If one takes the view that the array is a set then it *does* make sense to perform the block "for each" item "of" the "set".

**Comment by janat08** [comment]
What about going full on with custom element principles and adopting https://forums.donejs.com/t/weston-a-new-templating-engine-for-canjs-apps/468/4 skipping jsx, with react essentially doing same "ungodly" stuff like HOC '<hoc>my comp...</hoc>.

**Comment by janat08** [comment]
Also using template literals

**Comment by justinbmeyer** [comment]
@janat08 please create another proposal for what you are suggesting.

**Comment by justinbmeyer** [comment]
The scope lookup rule notes:

- `notContext` - Prevents `../` and such from accessing.
- `viewModel` - A special label, used so we can lookup the viewModel.
- `TemplateContext` - A special context instance type that is used to house variables for the template.  `scope.X` is used to look here.


Essentially, I think a basic "key" lookup like `{{foo}}` will look in (and walk) any variable scopes, and then look in the first `non-variable, non-notContext` scope it finds.

**Comment by matthewp** [comment]
I don't understand what imports is doing from the example. Why is one of them an element and one a stache helper? What's the difference between the two?

**Comment by justinbmeyer** [comment]
@matthewp it was just showing two different possibilities.

**Comment by justinbmeyer** [comment]
This should probably work:

```
{{#let selectedDriver}}
  <drivers-list selected:to="selectedDriver"/>
  <driver-edit driver="selectedDriver"/>
{{/let}}
```
